global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'oauth-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['oauth-server:3002']

  - job_name: 'ml-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-service:5000']

  - job_name: 'citizen-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['citizen-service:8000']

  - job_name: 'airquality-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['airquality-service:8001']

  - job_name: 'environment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['environment-service:8002']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']