apiVersion: v1
kind: ConfigMap
metadata:
  name: smartcity-config
  namespace: smartcity
data:
  NODE_ENV: "production"
  APP_ENV: "production"
  CORS_ORIGIN: "*"

  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "smartcity"
  AUTH_DB_NAME: "db_smartcity"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_EXCHANGE: "city.events"
  RABBITMQ_VHOST: "/"

  MQTT_HOST: "mosquitto"
  MQTT_PORT: "1883"

  AUTH_SERVICE_URL: "http://oauth-server:3002"
  OAUTH_SERVER_URL: "http://oauth-server:3002"
  CITIZEN_SERVICE_URL: "http://citizen-service:8000"
  AIRQUALITY_SERVICE_URL: "http://airquality-service:8001"
  ENVIRONMENT_SERVICE_URL: "http://environment-service:8002"
  PYTHON_ML_SERVICE_URL: "http://python-ml-service:5000"

  PORT_GATEWAY: "3000"
  PORT_AUTH: "3002"
  PORT_CITIZEN: "8000"
  PORT_AIRQUALITY: "8001"
  PORT_ENVIRONMENT: "8002"
  PORT_ML: "5000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: smartcity
data:
  00-create-databases.sql: |
    CREATE DATABASE IF NOT EXISTS smartcity CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS db_smartcity CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- TODO: replace this placeholder with the final schema.sql and seed.sql from Anggota B.
    -- Current purpose: keep MySQL ready for service-level integration testing.

