apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity
type: Opaque
data:
  # root
  DB_USER: cm9vdA==
  MYSQL_ROOT_USER: cm9vdA==

  # Empty password placeholder. Replace if the team decides to use a real password.
  DB_PASS: ""
  MYSQL_ROOT_PASSWORD: ""

  # guest
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASS: Z3Vlc3Q=

  # UAS_SE-2_2026_A
  JWT_ACCESS_SECRET: VUFTX1NFLTJfMjAyNl9B
  JWT_REFRESH_SECRET: VUFTX1NFLTJfMjAyNl9B

  # smartcity_internal_secret
  GATEWAY_INTERNAL_SECRET: c21hcnRjaXR5X2ludGVybmFsX3NlY3JldA==

